### ISSUE TITLE
Existen casos acumulados con un delta negativo respecto al caso anterior

### ISSUE THREAD

**Issue by FONDECYTACC** [jorgeperezrojas/covid19-data#12]
Hola, buenas noches, gracias por el aporte. Escribo para consultar por la naturaleza de los valores negativos en los casos acumulados (ej., valparaíso en 4/01/2020 muestra 26 casos acumulados, y luego al 04/03/2020 muestra 23) (adjunto excel con casos).
[casos_delta_neg](https://trello-attachments.s3.amazonaws.com/5eceeb0db31f8e7cef742248/5ed7d5a1caad515dbe1fb8d7/b40235ffb5775ce4d7f3dadd0552e998/casos_delta_neg.xlsx)

Saludos y gracias.

**Comment by juancri** [comment]
Sin saber la respuesta oficial, sospecho que son correcciones de datos temporales sobre el domicilio de los pacientes.

**Comment by jorgeperezrojas** [comment]
Sí, en general los datos que publicamos acá son los informados por el minsal en cada reporte. Ellos corrigen algunos números pero no lo hacen "retroactivamente" por lo que no podemos hacerlo tampoco nosotros. En general la forma mas "segura" de proceder es si es que hay un delta negativo, en fechas seguidas, entonces quedarse con el menor de los valores para la fecha más antigua. Creo que lo mejor es solucionarlo en el código y no cambiar los datos pues las fuentes oficiales no los cambian.

Saludos
