### ISSUE TITLE
Notificados =/= Exámenes realizados

### ISSUE THREAD

**Issue by damorend** [jorgeperezrojas/covid19-data#2]
Hola, los informes de Epidemiología informaban cifras de casos sospechosos notificados hasta el 31 de marzo. Esas cifras no coincidían con los reportes de exámenes realizados, ni en los dos días en que se traslapa la información de Epidemiología con las cifras de exámenes informados en los reportes diarios (30 y 31 de marzo), ni en el gráfico de exámenes que se incluyó en el informe de epidemiología del 23 de marzo.

El total acumulado de los "casos sospechosos notificados" siempre fue menor que el acumulado de "exámenes realizados", lo que puede tener varias explicaciones posibles (pura especulación de mi parte, no soy experto):

- En algún momento se contaron duplicados casos que hayan tenido más de un examen (creo recordar que el ministro dijo recientememte que no están haciendo eso hoy)
- En algún momento no se registraron todos los exámenes realizados como casos sospechosos en el sistema epivigilia.
- El sistema epivigilia tiene un retraso de un par de días en el registro de casos sospechosos respecto al conteo oficial de exámenes, tal como pasa con los casos confirmados. Esto significaría que hay un sistema de conteo rápido de exámenes distinto del sistema epivigilia.

**Comment by jorgeperezrojas** [comment]
Gracias por el comentario. Efectivamente los datos de "notificados" son muy ambiguos. Le agregamos un comentario a la descripción del archivo. En esta planilla puedes ver que hubo un cambio de nomenclatura en el reporte del Minsal https://docs.google.com/spreadsheets/d/1mLx2L8nMaRZu0Sy4lyFniDewl6jDcgnxB_d0lHG-boc/edit#gid=2051664207

**Comment by damorend** [comment]
Gracias, te dejé un par de comentarios en la planilla de drive

**Comment by jorgeperezrojas** [comment]
Gracias @damorend por todas tus observaciones. Creo que es más fácil comentar por acá. Respecto a tu comentario de que el "informe de situación" reporta los casos notificados hasta el mismo día del informe, creo que esto es incorrecto. Si miras el informe de situación del 31/03 dice 

```
El presente informe está desarrollado a partir de las 31.638 notificaciones disponibles en el sistema de vigilancia epidemiológica EPIVIGILA*, con un total de 2.744 casos confirmados, lo que representa una tasa de incidencia nacional de 14,1 casos por cien mil habitantes.
```

el número `2.744` coincide con la cantidad de casos confirmados informados el día 31/03 que informa casos hasta el día anterior (30/03) a las 21:00. Si bien tu tienes razón de que el informe de sitaución dice "al 31 de marzo", todo indica que los datos reportados incluyendo los casos notificados en el sistema Epivilga corresponden al día anterior.

Esto no subsana la aparente inconsistencia entre la cantidad de casos informados en Epivigila y la cantidad de exámenes notificados. Al parecer tu tienes razón que debe haber un conteo alternativo y me parece que debe venir desde los laboratorios. De hecho, desde el día 09/04 el Minsal informa los exámenes notificados por región del laboratorio y no por región de residencia del paciente.

Voy a tratar de aclarar todo esto en la planilla y el repositorio. Sería ideal que me comentaras si estás de acuerdo con mi análisis o si todavía hay algo que creas que no concuerda. Muchas gracias.
