### ISSUE TITLE
Eliminación de archivos antiguos

### ISSUE THREAD

**Issue by juancri** [jorgeperezrojas/covid19-data#22]
Hay archivos que no han sido actualizados en semanas o meses. La lista es:

- [csv/colombia_20200429.csv](https://github.com/jorgeperezrojas/covid19-data/blob/master/csv/colombia_20200429.csv)
- [csv/long_encuesta_sochimi.csv](https://github.com/jorgeperezrojas/covid19-data/blob/master/csv/long_encuesta_sochimi.csv)
- [csv/long_regiones.csv](https://github.com/jorgeperezrojas/covid19-data/blob/master/csv/long_regiones.csv)
- [csv/mexico_20200429.csv](https://github.com/jorgeperezrojas/covid19-data/blob/master/csv/mexico_20200429.csv)

¿Podemos eliminarlos?

**Comment by jorgeperezrojas** [comment]
No había visto este issue. Los archivos de mexico y colombia no deberíamos eliminarlos porque acompañan a un documento "histórico" que fue publicado a fines de abril.  Los otros dos archivos (los long) podemos borrarlos porque ya no están en uso. Puedes hacerlo tu?

**Comment by juancri** [comment]
OK, envío el PR.
