### ISSUE TITLE
OHiggins bajó su total por un día

### ISSUE THREAD

**Issue by juancri** [jorgeperezrojas/covid19-data#28]
En el archivo [confirmados.csv](/jorgeperezrojas/covid19-data/blob/master/csv/confirmados.csv), la región de O’Higgins disminuyó la cantidad de casos acumulados:

- **07/23/2020:** 9817
- **07/24/2020:** 979
- **07/25/2020:** 10083

Por ahora, voy a agregar tests para esto. Actualizo el issue cuando tenga un PR.

**Comment by sanguineti** [comment]
solucionado :)
