### ISSUE TITLE
Fechas como columnas?

### ISSUE THREAD

**Issue by samuelsoc** [jorgeperezrojas/covid19-data#3]
Estimado, en primer lugar valoro la iniciativa y esfuerzo que han puesto en la creación de este repositorio con datos e información actualizada, sobre la contingencia del covid19 en Chile. Sin embargo al ver los datos, no puedo dejar de pensar por qué tienen las fechas como columnas? 
Al ver su perfil en Github, veo que domina temas de teoria de base de datos, web semántica entre otros, y supongo que tienen alguna razon para presentar con esa estructura los datos.
 Mi inquietud al ver esta estructura surge porque en mi experiencia trabajando con datos, creo que las fechas se manejan de mejor manera dentro de una sola columna, agregando los datos nuevos hacia abajo. En lo práctico el consumo de datos via API, por ejemplo, la fecha siempre (o casi siempre), será una columna. Me gustaría saber la razón de esta presentación, más bien de curioso. Saludos.

**Comment by ivanMSC** [comment]
@samuelsoc Es el formato estándar para presentar los datos del Covid19 por ubicación geográfica (formato que usa el JHU). Usted puede fácilmente despivotear la tabla en su terminal.
Ahora si eso le parece tedioso, en mi [repo ](https://github.com/ivanMSC/COVID19_Chile) posiblemente encontrará lo que busca.

**Comment by jorgeperezrojas** [comment]
hola @samuelsoc como dice @ivanMSC una de las razones es dejarlos de manera de que sean comparables con datos reportados (antes que nosotros) por otras fuentes. Hay una iniciativa para pasar todos estas fuentes a una BD relacional que se nutra desde distintos repositorios, donde por las razones que tu expresas no tendría sentido poner las fechas como columnas. A penas pueda les doy el enlace. Respecto de APIs aquí hay un esfuerzo para simplificar el acceso por si quieres aportar ahí: https://github.com/sanguineti/chile-coronapi

Saludos

**Comment by samuelsoc** [comment]
@ivanMSC de hecho, antes de llegar acá estaba (más bien estoy) usando tu repo. Y claro, mi duda era cuál era razón de presentar de esta forma, y fue respondida, la transformación no es un drama. @jorgeperezrojas  Gracias por la pronta respuesta.
