### ISSUE TITLE
Fecha repetida en csv resumen_nacional

### ISSUE THREAD

**Issue by Jonskadev** [jorgeperezrojas/covid19-data#4]
Aprovechando de agradecer la iniciativa que conlleva este repo, revisando los datos me di cuenta de que en la segunda fila, la fecha está mal puesta (dice 04/08/2020 cuando debería decir 03/08/2020),
Saludos y gracias!
![imagen](https://user-images.githubusercontent.com/9122377/79193297-56369300-7df8-11ea-8aca-bd7311cc52b4.png)

**Comment by sanguineti** [comment]
@Jonskadev  Gracias por reportar el problema, ya está corregido!
