### ISSUE TITLE
pcrs leyendose mal

### ISSUE THREAD

**Issue by verasativa** [jorgeperezrojas/covid19-data#5]
Hola, parece que los pcrs se estan leyendo mal. Si se fijan en los ultimos csv hay regiones en cero, pero el ultimo pdf del minsal no.

**Comment by jorgeperezrojas** [comment]
Gracias por el comentario. Para el 17/04 (la última fecha actualizada hasta el momento en el csv de pcrs) Tarapacá y Coquimbo tienen 0 pcrs lo que es consistente con este informe https://cdn.digital.gob.cl/public_files/Campa%C3%B1as/Corona-Virus/Reportes/17.04.2020_Reporte_Covid19.pdf

Los pcrs al 18/04 todavía no se actualizan (ya vienen!) y también hay varias regiones con 0. Puedes seguir los datos actualizados acá: https://docs.google.com/spreadsheets/d/1mLx2L8nMaRZu0Sy4lyFniDewl6jDcgnxB_d0lHG-boc/edit#gid=2051664207

Dime porfa si responde tu duda o si aun ves alguna inconsistencia. Gracias!
